### ISSUE TITLE
Implementing Music Commands

### ISSUE THREAD

**Issue by MutlaqAldhbuiub** [sudogroup/SudoBot#19]
**Is your feature request related to a problem? Please describe.**
The bot doesn't have a way to listen for any music or sound. In addition, it is beneficial to have the ability to control the volume and additional features like repeating the sound, the URL of it, and skip it(move to the next sound).

**Describe the solution you'd like**
Implementing those Music/Sound commands

- [x] play [song]: play song
- [x] stop [song]: stop song and leave the channel
- [x] skip [song] : move to the next song
- [x] pause: pause song
- [x] resume: resume song
- [x] repeat: repeats the current song
- [x] song: get the current song's title and URL

**Comment by sudomaze** [comment]
I got this error when trying to play a song: 

`Error: input stream: Could not find player config`

and

`Error: input stream: Video unavailable`
